In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT m.surname, m.firstname, m.recommendedby AS recomender_id, r.surname AS recomender_surname, r.firstname AS recomender_firstname FROM Members AS m LEFT JOIN Members AS r ON m.recommendedby = r.memid WHERE m.recommendedby != 0 ORDER BY r.surname, r.firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST', 'GUEST', '', None, None)
('Smith', 'Darren', '', None, None)
('Smith', 'Tracy', '', None, None)
('Rownam', 'Tim', '', None, None)
('Tracy', 'Burton', '', None, None)
('Farrell', 'Jemima', '', None, None)
('Farrell', 'David', '', None, None)
('Tupperware', 'Hyacinth', '', None, None)
('Smith', 'Darren', '', None, None)
('Sarwin', 'Ramnaresh', '15', 'Bader', 'Florence')
('Coplin', 'Joan', '16', 'Baker', 'Timothy')
('Genting', 'Matthew', '5', 'Butters', 'Gerald')
('Baker', 'Timothy', '13', 'Farrell', 'Jemima')
('Pinker', 'David', '13', 'Farrell', 'Jemima')
('Rumney', 'Henrietta', '20', 'Genting', 'Matthew')
('Jones', 'Douglas', '11', 'Jones', 'David')
('Dare', 'Nancy', '4', 'Joplette', 'Janice')
('Jones', 'David', '4', 'Joplette', 'Janice')
('Hunt', 'John', '30', 'Purview', 'Millicent')
('Boothe', 'Tim', '3', 'Rownam', 'Tim')
('Joplette', 'Janice', '1', 'Smith', 'Darren')
('Butters', 'Gerald', '1', 'Smith', 'Darren')
('Owen', 'Charles', '1', 'Smith', 'Darren')
('Smith', 'Jack', '1', 'Smith', 'Darren')
('Mackenzie', 'Anna', '1', 'Smith', 'Darren')
('Worthington-Smyth', 'Henry', '2', 'Smith', 'Tracy')
('Purview', 'Millicent', '2', 'Smith', 'Tracy')
('Crumpet', 'Erica', '2', 'Smith', 'Tracy')
('Baker', 'Anne', '9', 'Stibbons', 'Ponder')
('Bader', 'Florence', '9', 'Stibbons', 'Ponder')
('Stibbons', 'Ponder', '6', 'Tracy', 'Burton')

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
     SELECT m.surname, m.firstname, m.recommendedby AS recomender_id, r.surname AS recomender_surname, r.firstname AS recomender_firstname
FROM Members AS m
LEFT JOIN Members AS r ON m.recommendedby = r.memid
WHERE m.recommendedby != 0
ORDER BY r.surname, r.firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST', 'GUEST', '', None, None)
('Smith', 'Darren', '', None, None)
('Smith', 'Tracy', '', None, None)
('Rownam', 'Tim', '', None, None)
('Tracy', 'Burton', '', None, None)
('Farrell', 'Jemima', '', None, None)
('Farrell', 'David', '', None, None)
('Tupperware', 'Hyacinth', '', None, None)
('Smith', 'Darren', '', None, None)
('Sarwin', 'Ramnaresh', '15', 'Bader', 'Florence')
('Coplin', 'Joan', '16', 'Baker', 'Timothy')
('Genting', 'Matthew', '5', 'Butters', 'Gerald')
('Baker', 'Timothy', '13', 'Farrell', 'Jemima')
('Pinker', 'David', '13', 'Farrell', 'Jemima')
('Rumney', 'Henrietta', '20', 'Genting', 'Matthew')
('Jones', 'Douglas', '11', 'Jones', 'David')
('Dare', 'Nancy', '4', 'Joplette', 'Janice')
('Jones', 'David', '4', 'Joplette', 'Janice')
('Hunt', 'John', '30', 'Purview', 'Millicent')
('Boothe', 'Tim', '3', 'Rownam', 'Tim')
('Joplette', 'Janice', '1', 'Smith', 'Darren')
('Butters', 'Gerald', '1', 'Smith', 'Darren')
('Owen', 'Charles', '1', 'Smith', 'Darren')
('Smith', 'Jack', '1', 'Smith', 'Darren')
('Mackenzie', 'Anna', '1', 'Smith', 'Darren')
('Worthington-Smyth', 'Henry', '2', 'Smith', 'Tracy')
('Purview', 'Millicent', '2', 'Smith', 'Tracy')
('Crumpet', 'Erica', '2', 'Smith', 'Tracy')
('Baker', 'Anne', '9', 'Stibbons', 'Ponder')
('Bader', 'Florence', '9', 'Stibbons', 'Ponder')
('Stibbons', 'Ponder', '6', 'Tracy', 'Burton')

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
     SELECT f.name AS facilityname, COUNT(*) AS usage_by_members
FROM Bookings AS b
LEFT JOIN Facilities AS f ON b.facid = f.facid
LEFT JOIN Members AS m ON b.memid = m.memid
WHERE b.memid != 0
GROUP BY f.name
ORDER BY usage_by_members DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 783)
('Snooker Table', 421)
('Massage Room 1', 421)
('Table Tennis', 385)
('Badminton Court', 344)
('Tennis Court 1', 308)
('Tennis Court 2', 276)
('Squash Court', 195)
('Massage Room 2', 27)

In [5]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT f.name AS facilityname, 
    strftime('%m', date(b.starttime)) AS month, 
    COUNT(*) AS facility_usage 
    FROM Bookings AS b 
JOIN Facilities AS f ON b.facid = f.facid 
WHERE b.memid != 0 
GROUP BY facilityname, month 
ORDER BY facilityname, month;        
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', '07', 51)
('Badminton Court', '08', 132)
('Badminton Court', '09', 161)
('Massage Room 1', '07', 77)
('Massage Room 1', '08', 153)
('Massage Room 1', '09', 191)
('Massage Room 2', '07', 4)
('Massage Room 2', '08', 9)
('Massage Room 2', '09', 14)
('Pool Table', '07', 103)
('Pool Table', '08', 272)
('Pool Table', '09', 408)
('Snooker Table', '07', 68)
('Snooker Table', '08', 154)
('Snooker Table', '09', 199)
('Squash Court', '07', 23)
('Squash Court', '08', 85)
('Squash Court', '09', 87)
('Table Tennis', '07', 48)
('Table Tennis', '08', 143)
('Table Tennis', '09', 194)
('Tennis Court 1', '07', 65)
('Tennis Court 1', '08', 111)
('Tennis Court 1', '09', 132)
('Tennis Court 2', '07', 41)
('Tennis Court 2', '08', 109)
('Tennis Court 2', '09', 126)